app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2

mongo:
  url: 'mongodb://localhost:27017'
  user: ''
  password: ''
  name: 'chess'
  
rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'

grpc:
  ip: 'localhost'
  port: 50551